CREATE SCHEMA GESTION;

DROP TABLE GESTION.BUREAU;
DROP TABLE GESTION.MESSAGE;
DROP TABLE GESTION.RESPONSABLE;
DROP TABLE GESTION.PERSONNE;

CREATE TABLE GESTION.PERSONNE(
    PERSONNE_ID INTEGER NOT NULL,
    NOM VARCHAR(30) NOT NULL,
    PRENOM VARCHAR(30) NOT NULL,
    MAIL VARCHAR(60) NOT NULL,
    EQUIPE VARCHAR(10) NOT NULL,
    DATE_DEBUT DATE,
    DATE_FIN DATE
);
ALTER TABLE GESTION.PERSONNE ADD CONSTRAINT PERSONNE_PK PRIMARY KEY (PERSONNE_ID);


CREATE TABLE GESTION.BUREAU(
    BUREAU_ID INTEGER NOT NULL,
    BATIMENT VARCHAR(1),
    NUMERO VARCHAR(3) NOT NULL,
    ETAGE VARCHAR(1) NOT NULL,
    NB_MAX_PERSONNE INTEGER NOT NULL
);
ALTER TABLE GESTION.BUREAU ADD CONSTRAINT BUREAU_PK PRIMARY KEY (BUREAU_ID);
ALTER TABLE GESTION.BUREAU ADD CONSTRAINT BUREAU_UNIQUE UNIQUE (BATIMENT, NUMERO, ETAGE);
ALTER TABLE GESTION.BUREAU ADD CONSTRAINT BATIMENT_CK CHECK (BATIMENT IN ('A', 'B'));
ALTER TABLE GESTION.BUREAU ADD CONSTRAINT ETAGE_CK CHECK (ETAGE IN ('1', '2', '3'));
 /* TODO    
ALTER TABLE GESTION.BUREAU ADD CONSTRAINT NUMERO_CK CHECK (NUMERO LIKE ''); 
*/



CREATE TABLE GESTION.MESSAGE(
    MESSAGE_ID INTEGER NOT NULL,
    TEXTE VARCHAR(300) NOT NULL,
    DATE_MESSAGE DATE,
    PERSONNE_ID INTEGER
);

ALTER TABLE GESTION.MESSAGE ADD CONSTRAINT MESSAGE_PK PRIMARY KEY (MESSAGE_ID);
ALTER TABLE GESTION.MESSAGE ADD CONSTRAINT MESSAGE_FK FOREIGN KEY (PERSONNE_ID) REFERENCES GESTION.PERSONNE(PERSONNE_ID);


CREATE TABLE GESTION.RESPONSABLE(
    PERSONNE_ID INTEGER NOT NULL,
    IDENTIFIANT VARCHAR(30),
    MOT_DE_PASSE VARCHAR(30)
);
ALTER TABLE GESTION.RESPONSABLE ADD CONSTRAINT RESPONSABLE_PK PRIMARY KEY (PERSONNE_ID);
ALTER TABLE GESTION.RESPONSABLE ADD CONSTRAINT RESPONSABLE_FK FOREIGN KEY (PERSONNE_ID) REFERENCES GESTION.PERSONNE(PERSONNE_ID);

