DROP TABLE BUREAU;
DROP TABLE MESSAGE;
DROP TABLE RESPONSABLE;
DROP TABLE PERSONNE;

CREATE TABLE PERSONNE(
    PERSONNE_ID integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOM VARCHAR(30) NOT NULL,
    PRENOM VARCHAR(30) NOT NULL,
    MAIL VARCHAR(60) NOT NULL,
    EQUIPE VARCHAR(10) NOT NULL,
    DATE_DEBUT DATE NOT NULL,
    DATE_FIN DATE,
    BUREAU_ID integer
);
ALTER TABLE PERSONNE ADD CONSTRAINT PERSONNE_FK FOREIGN KEY (BUREAU_ID) REFERENCES BUREAU(BUREAU_ID);


CREATE TABLE BUREAU(
    BUREAU_ID integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    BATIMENT VARCHAR(1),
    NUMERO VARCHAR(3) NOT NULL,
    ETAGE VARCHAR(1) NOT NULL,
    NB_MAX_PERSONNE INTEGER NOT NULL
);
ALTER TABLE BUREAU ADD CONSTRAINT BUREAU_UNIQUE UNIQUE (BATIMENT, NUMERO, ETAGE);
ALTER TABLE BUREAU ADD CONSTRAINT BATIMENT_CK CHECK (BATIMENT IN ('A', 'B'));
    
/*ALTER TABLE GESTION.BUREAU ADD CONSTRAINT NUMERO_CK CHECK (NUMERO LIKE ''); */

ALTER TABLE BUREAU ADD CONSTRAINT ETAGE_CK CHECK (ETAGE IN ('1', '2', '3'));



CREATE TABLE MESSAGE(
    MESSAGE_ID integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TEXTE VARCHAR(300) NOT NULL,
    DATE_MESSAGE DATE,
    PERSONNE_ID INTEGER
);
ALTER TABLE MESSAGE ADD CONSTRAINT MESSAGE_FK FOREIGN KEY (PERSONNE_ID) REFERENCES PERSONNE(PERSONNE_ID);


CREATE TABLE RESPONSABLE(
    PERSONNE_ID integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IDENTIFIANT VARCHAR(30),
    MOT_DE_PASSE VARCHAR(30)
);
ALTER TABLE RESPONSABLE ADD CONSTRAINT RESPONSABLE_FK FOREIGN KEY (PERSONNE_ID) REFERENCES PERSONNE(PERSONNE_ID);

